<?php /** @var \Facebook\BusinessExtension\Block\Pixel\Head $block */ ?>
<?php if ($block->getFacebookPixelID()) { ?>
<!-- Meta Business Extension for Magento 2 -->
<!-- Meta Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');
    <?php
    $dataProcessingOptionsCode = $block->getDataProcessingOptionsJSCode();
    if (strlen($dataProcessingOptionsCode) > 0) {
        echo $dataProcessingOptionsCode."\n";
    }
    ?>
fbq(
  'init',
  '<?= $block->getFacebookPixelID() ?>',
    <?= $block->getPixelInitCode() ?>,
  {agent: '<?= $block->getFacebookAgentVersion() ?>' }
);
fbq('track', 'PageView', {
  source: "<?= $block->getSource() ?>",
  pluginVersion: "<?= $block->getPluginVersion() ?>"
});
</script>
<noscript>
    <?php
    $dataProcessingOptionsImgTag = $block->getDataProcessingOptionsImgTag();
    if (strlen($dataProcessingOptionsImgTag) == 0) {
        ?>
<img height="1" width="1" style="display:none"
     src="https://www.facebook.com/tr?id=<?= $block->getFacebookPixelID() ?>&ev=PageView&noscript=1&a=<?= $block->getFacebookAgentVersion() ?>" />
        <?php
    } else {
        ?>
<img height="1" width="1" style="display:none"
     src="https://www.facebook.com/tr?id=<?= $block->getFacebookPixelID() ?>&ev=PageView&noscript=1&a=<?= $block->getFacebookAgentVersion() ?>&<?= $dataProcessingOptionsImgTag ?>" />
        <?php
    }
    ?>
</noscript>
<!-- End Meta Pixel Code -->
<?php } else { ?>
<!-- NO Pixel ID is configured, please goto Admin -->
<script>
console.log('No Meta pixel is configured, please log in as a admin and then visit Stores -> Meta -> Setup -> Get Started');
</script>
<?php } ?>
