<?php
/** @var \Facebook\BusinessExtension\Block\Pixel\InitiateCheckout $block */
if ($block->getFacebookPixelID()) {
    $eventId = \Facebook\BusinessExtension\Helper\EventIdGenerator::guidv4();
    $block->trackServerEvent($eventId);
    ?>
    <script>
        fbq('set', 'agent', '<?= $block->getFacebookAgentVersion() ?>', '<?= $block->getFacebookPixelID() ?>');
        fbq('track', 'InitiateCheckout', {
                source: "<?= $block->getSource() ?>",
                pluginVersion: "<?= $block->getPluginVersion() ?>",
                content_type: "<?= $block->getContentType() ?>",
                content_ids: [<?= $block->getContentIDs() ?>],
                num_items: <?= $block->getNumItems() ?>,
                contents: [<?= $block->getContents() ?>]
                <?php if ($block->getValue() && $block->getCurrency()) { ?>
                , value: <?= $block->getValue() ?>
                , currency: "<?= $block->getCurrency() ?>"
                <?php } ?>
            }
            , {
                eventID: "<?= $eventId ?>"
            }
        );
    </script>
    <?php $block->logEvent($block->getFacebookPixelID(), 'InitiateCheckout') ?>
<?php } ?>
