<?php
if ($block->getFacebookPixelID()) {
    $eventId = \Facebook\BusinessExtension\Helper\EventIdGenerator::guidv4();
    $block->trackServerEvent($eventId);
    ?>
<script>
fbq('set', 'agent', '<?= $block->getFacebookAgentVersion() ?>', '<?= $block->getFacebookPixelID() ?>');
fbq('track', 'Search', {
    source: "<?= $block->getSource() ?>",
    version: "<?= $block->getMagentoVersion() ?>",
    pluginVersion: "<?= $block->getPluginVersion() ?>",
    search_string: "<?= $block->getSearchQuery() ?>"
  }
  ,{
    eventID:  "<?= $eventId ?>"
  }
);
</script>
    <?php $block->logEvent($block->getFacebookPixelID(), 'Search') ?>
<?php } ?>
