<?php
/** @var \Facebook\BusinessExtension\Block\Pixel\ViewCategory $block */
if ($block->getFacebookPixelID()) {
    $eventId = \Facebook\BusinessExtension\Helper\EventIdGenerator::guidv4();
    $block->trackServerEvent($eventId);
    ?>
    <script>
        fbq('set', 'agent', '<?= $block->getFacebookAgentVersion() ?>', '<?= $block->getFacebookPixelID() ?>');
        fbq('trackCustom', 'ViewCategory', {
                source: "<?= $block->getSource() ?>",
                pluginVersion: "<?= $block->getPluginVersion() ?>"
                <?php if ($block->getCategory()) { ?>
                , content_category: "<?= $block->getCategory() ?>"
                <?php } ?>
            }
            , {
                eventID: "<?= $eventId ?>"
            }
        );
    </script>
    <?php $block->logEvent($block->getFacebookPixelID(), 'ViewCategory') ?>
<?php } ?>
