<?php
/* @var \Facebook\BusinessExtension\Block\Pixel\ViewContent $block */
if ($block->getFacebookPixelID()) {
    $eventId = \Facebook\BusinessExtension\Helper\EventIdGenerator::guidv4();
    $block->trackServerEvent($eventId);
    ?>
    <script>
        fbq('set', 'agent', '<?= $block->getFacebookAgentVersion() ?>', '<?= $block->getFacebookPixelID() ?>');
        fbq('track', 'ViewContent', {
                source: "<?= $block->getSource() ?>",
                pluginVersion: "<?= $block->getPluginVersion() ?>",
                content_type: "<?= $block->getContentType() ?>",
                content_ids: [<?= $block->getContentIDs() ?>]
                <?php if ($block->getContentName()) { ?>
                , content_name: "<?= $block->getContentName() ?>"
                <?php } ?>
                <?php if ($block->getContentCategory()) { ?>
                , content_category: "<?= $block->getContentCategory() ?>"
                <?php } ?>
                <?php if ($block->getValue() && $block->getCurrency()) { ?>
                , value: <?= $block->getValue() ?>
                , currency: "<?= $block->getCurrency() ?>"
                <?php } ?>
            }
            , {
                eventID: "<?= $eventId ?>"
            }
        );
    </script>
    <?php $block->logEvent($block->getFacebookPixelID(), 'ViewContent') ?>
<?php } ?>
