<?php /** @var Facebook\BusinessExtension\Block\Adminhtml\Setup $block */ ?>
<div>
    <div id="fbe-iframe">
    </div>
</div>

<script>
    window.facebookBusinessExtensionConfig = {
        pixelId: '<?= $block->fetchPixelId() ?>'
        , popupOrigin: "https://business.facebook.com"
        , setPixelId: '<?= $block->getPixelAjaxRoute() ?>'
        , setAccessToken: '<?= $block->getAccessTokenAjaxRoute() ?>'
        , setProfilesData: '<?= $block->getProfilesAjaxRoute()?>'
        , setFeedPush: '<?= $block->getFeedPushAjaxRoute() ?>'
        , externalBusinessId: '<?= $block->getExternalBusinessId()?>'
        , fbeLoginUrl: "https://business.facebook.com/fbe-iframe-get-started/?"
        , deleteConfigKeys: '<?= $block->getDeleteAssetIdsAjaxRoute() ?>'
        , appId: '195311308289826'
        , timeZone: 'America/Los_Angeles'
        , installed: '<?= $block->isFBEInstalled() ?>'
        , systemUserName: '<?= $block->getExternalBusinessId() ?>' + '_system_user'
        , businessVertical: 'ECOMMERCE'
        , channel: 'COMMERCE_OFFSITE'
        , currency: '<?= $block->getCurrencyCode() ?>'
        , businessName: 'Magento'
        , debug: true
        , setAAMSettings: '<?= $block->getAAMSettingsRoute() ?>'
    };
</script>
<script>
    require([
        'Facebook_BusinessExtension/js/fbe_allinone'
    ], function () {
    });
</script>
